/*  ACÁ SÓLO CÓDIGO COMENTADO */
/* PARA GUARDAR NOTAS SOBRE CÓDIGO O LINEAS QUE NOS PUEDEN SERVIR

para correr la máquina y abortarla, teclas que podemos usar
KEY_HOME
KEY_UP
KEY_PGUP
KEY_LEFT
KEY_CENTER
KEY_RIGHT
KEY_END
KEY_DOWN
KEY_PGDN
KEY_INSERT
KEY_DELETE

*/
